name: rtsp_server
description: rtsp server
version: 0.0.1
homepage: https://github.com/xiaohuihuiold/rtsp_server
repository: https://github.com/xiaohuihuiold/rtsp_server

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.3.0
  date_format: ^2.0.7
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
